platform:
  - x86

install:
  - ps: Install-Product node 8.9.1
  - npm install -g yarn
  - git submodule update --init --recursive
  - choco install -y InnoSetup
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

build_script:
  - yarn
  - yarn run client-build-win

artifacts:
  - path: build\prod-client-build\Setup.exe
  - path: build\prod-client-buildwin32-package.tar.gz
