platform:
  - x86

install:
  - ps: Install-Product node 8.9.1
  - npm install -g yarn
  - git submodule update --init --recursive
  - choco install -y InnoSetup
  - set PATH="C:\ProgramData\chocolatey\bin";%PATH%

build_script:
  - yarn
  - yarn run client-build-win

# Maybe this will work to tell it there's no tests.
test_script:

artifacts:
  - path: build\prod-client-build\Setup.exe
  - path: build\prod-client-build\win32-package.tar.gz
