version: 2
jobs:
   build:
     macos:
      xcode: "9.0"
     steps:
       - checkout
       - run: 'git submodule update --init --recursive'
       - run: 'yarn'
       - run: 'yarn run client-build-osx'
       - store_artifacts:
           path: ./build/prod-client-build/osx64-package.zip
       - store_artifacts:
           path: ./build/prod-client-build/osx.dmg
