version: 2
jobs:
   build:
     macos:
      xcode: "9.0"
     steps:
       - checkout
       - run: 'git clone https://github.com/creationix/nvm.git ./.nvm'
       - run: 'source ./.nvm/nvm.sh'
       - run: 'nvm install 8.9.1'
       - run: 'nvm use 8.9.1'
       - run: 'npm i -g yarn'
       - run: 'yarn'
       - run: 'yarn run client-build-osx'
